version: '3.0'
services:
  dev:
    image: thermakube/kube-prod
    container_name: 'thermakube-prod'
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
volumes:
  node_modules:
